### PR TITLE
Fix closing of connection, address various minor issues and code smells, improve options and overall usability

### LINKED ISSUE #24: The close() method does not reliably close the SSE connection
Consider the following example:

```ts
let sse = new EventSource('https://httpstat.us/404', {
    debug: true,
    pollingInterval: 10000,
});

sse.addEventListener('error', (e) => {
    console.log('There was an error:', e);
    console.log('Closing SSE');
    sse.close();
});
```

The `httpstat.us/404` endpoint always returns a 404 error status. Since I call `sse.close()` in the error handler, I would expect the SSE connection be closed pretty much immediately after it is created. However, this is not the case. If I run the above code, the SSE keeps trying to reconnect every 10 seconds . Apparently, calling `sse.close()` does not properly stop the pollingInterval. Here are the logs I get when running the above code (it keeps repeating every 10 seconds):

```
 DEBUG  [EventSource][onreadystatechange] ReadyState: 2, status: 404
 DEBUG  [EventSource][onreadystatechange] ReadyState: 3, status: 404
 LOG  There was an error: {"message": "404 Not Found", "type": "error", "xhrState": 3, "xhrStatus": 404}
 LOG  Closing SSE
 DEBUG  [EventSource][onreadystatechange] ReadyState: 4, status: 0
 DEBUG  [EventSource][onreadystatechange][ERROR] Response status error. Reconnecting...
 DEBUG  [EventSource][onreadystatechange] ReadyState: 2, status: 404
 DEBUG  [EventSource][onreadystatechange] ReadyState: 3, status: 404
 LOG  There was an error: {"message": "404 Not Found", "type": "error", "xhrState": 3, "xhrStatus": 404}
 LOG  Closing SSE
 DEBUG  [EventSource][onreadystatechange] ReadyState: 4, status: 0
 DEBUG  [EventSource][onreadystatechange][ERROR] Response status error. Reconnecting...
 DEBUG  [EventSource][onreadystatechange] ReadyState: 2, status: 404
 DEBUG  [EventSource][onreadystatechange] ReadyState: 3, status: 404
 LOG  There was an error: {"message": "404 Not Found", "type": "error", "xhrState": 3, "xhrStatus": 404}
 LOG  Closing SSE
 DEBUG  [EventSource][onreadystatechange] ReadyState: 4, status: 0
 DEBUG  [EventSource][onreadystatechange][ERROR] Response status error. Reconnecting...
```

If I change the error handler to only close the SSE after waiting one second (using `setTimeout`), then it works:

```ts
let sse = new EventSource('https://httpstat.us/404', {
    debug: true,
    pollingInterval: 10000,
});

sse.addEventListener('error', (e) => {
    console.log('There was an error:', e);
    setTimeout(() => {
        console.log('Closing SSE');
        sse.close();
    }, 1000);
});
```

The 404 error is yielded twice for some reason, but this time closing the connection works:

```
 DEBUG  [EventSource][onreadystatechange] ReadyState: 2, status: 404
 DEBUG  [EventSource][onreadystatechange] ReadyState: 3, status: 404
 LOG  There was an error: {"message": "404 Not Found", "type": "error", "xhrState": 3, "xhrStatus": 404}
 DEBUG  [EventSource][onreadystatechange] ReadyState: 4, status: 404
 LOG  There was an error: {"message": "404 Not Found", "type": "error", "xhrState": 4, "xhrStatus": 404}
 DEBUG  [EventSource][onreadystatechange][ERROR] Response status error. Reconnecting...
 LOG  Closing SSE
 LOG  Closing SSE
```

In my opinion, this is a pretty serious bug. The SSE should always stop all its activity when the `close()` method is called. It certainly shouldn't try to auto-reconnect after this method was called.

### LINKED ISSUE #28: Allow set withCredentials property on XMLHttpRequest object
Would be cool to have a possibility to set withCredentials prop on XMLHttpRequest.

### PR DESCRIPTION
**Pull request by EmilJunker**
This PR addresses various (mostly minor) issues and code smells I stumbled accross while using this package. Most notably, it resolves #24.

Update (2023-09-22): I have now updated this PR to also close #28.

I have kept my commits nice and small, so it should be easy to verify that they all make sense :)

### CODE REVIEW

**Comment by yaxiaoliu** [comment]
Do you have any release plans?

**Comment by EmilJunker** [comment]
> Do you have any release plans?

@wojciechkrol Are you still maintaining this project? If you are looking for a new maintainer, I would be willing to help. I am an experienced JavaScript developer and deal a lot with SSE connections for my work.

**Comment by RalissonMattias** [comment]
Up +1

**Comment by RalissonMattias** [comment]
> > Do you have any release plans?
> 
> @wojciechkrol Are you still maintaining this project? If you are looking for a new maintainer, I would be willing to help. I am an experienced JavaScript developer and deal a lot with SSE connections for my work.

Maybe you can create a fork and release a new library

**Comment by EmilJunker** [comment]
> Maybe you can create a fork and release a new library

I would prefer not to create unnecessarily fragmentation for users. Why make a new library when this one already exists and is used by thousands of people. All I'm asking for is that the maintainers of this repository do their job. And if they have lost interest in this project, they can simply pass it on to new maintainers. Happens all the time. No big deal.

**Comment by RalissonMattias** [comment]
> > Maybe you can create a fork and release a new library
> 
> I would prefer not to create unnecessarily fragmentation for users. Why make a new library when this one already exists and is used by thousands of people. All I'm asking for is that the maintainers of this repository do their job. And if they have lost interest in this project, they can simply pass it on to new maintainers. Happens all the time. No big deal.

Yes, I have the same thought as you, I'm just worried that some maintainers take months to respond, sometimes they don't even respond, but I'm happy that there are people trying to keep the project alive. Good job!

**Comment by wojciechkrol** [comment]
Hello Everyone,

I'm sorry I didn't respond to your submissions. Thank you all for your suggestions and concern for the library's development. Of course, I intend to continue developing it, but due to time spent on other projects, I've been unable to make progress in this area.

Today, I will review your pull requests and submissions, and will strive to implement the necessary changes.

Thank you for being so patient!

**Pull request merged**
