### PR TITLE
docs: Update readme

### PR DESCRIPTION
**Pull request by Lenny4**

### CODE REVIEW

**Comment by Lenny4** [comment]
@binaryminds please tell me if my explanation is clear.

**Comment by wojciechkrol** [comment]
Hi @Lenny4,

Thank you for contributing.

Your solution is not good and does not resolve the problem with access to the actual redux state from a listener. Since the listener is a closure it has access only to the component values from the first render. Each concurrent render does not affect already defined listeners.

Here you have a similar situation with `setInterval`: https://stackoverflow.com/questions/53024496/state-not-updating-when-using-react-state-hook-within-setinterval

If you use Redux you can get the actual value directly from the store instance. Look at my example on Expo Snack: https://snack.expo.dev/@quiknull/react-native-sse-redux-example

Feel free to update docs with this solution.

**Comment by Lenny4** [comment]
@wojciechkrol is it better now ?

**Comment by Lenny4** [comment]
Hi @wojciechkrol , i'm still waiting for an answer

**Comment by wojciechkrol** [comment]
Hi @Lenny4. Thank you for the update.

- Please remove .gitignore, since it is not connected with PR.
- Please rename "Warning (react-redux)" to "Usage with React Redux". It shouldn't be a warning. It should help users to understand how listeners work in the context of react-redux.
- Make this section be the last sub-section of Usage.

Thank you!

**Comment by Lenny4** [comment]
@wojciechkrol done !

**Pull request merged**
