### PR TITLE
fix types

### PR DESCRIPTION
**Pull request by ingvardm**
This PR should fix issue #8 and other issues regarding event types and callback arguments.

### CODE REVIEW

**Review by yogesh2902 — APPROVED** [review]

**Comment by EmilJunker** [comment]
This looks very good to me. It fixes the problem described in #8 and also makes sense code-wise. Could somebody merge this please? Maybe you @wojciechkrol?

**Comment by wojciechkrol** [comment]
It doesn't fix the problem and introduces new one:

image

**Comment by EmilJunker** [comment]
@wojciechkrol I can assure you that this works perfectly. Are you using it like this?

```ts
type MyCustomEvents = 'ping' | 'clientConnected' | 'clientDisconnected';

const es = new EventSource<MyCustomEvents>('https://your-sse-server.com/');

es.addEventListener('open', (event) => {
    console.log('Open SSE connection:', event);
});

es.addEventListener('message', (event) => {
    console.log('Received SSE message:', event);
});

es.addEventListener('error', (event) => {
    console.log('SSE error:', event);
});

es.addEventListener('ping', (event) => {
    console.log('Received ping:', event);
});

es.addEventListener('clientConnected', (event) => {
    console.log('Client connected:', event);
});

es.addEventListener('clientDisconnected', (event) => {
    console.log('Client disconnected:', event);
});
```

**Comment by wojciechkrol** [comment]
@EmilJunker I have a single listener handling multiple event types as shown:

```ts
const listener: EventSourceListener<MyCustomEvents> = (event) => {
  // ...
  if (event.type === 'open') {
    // ...
  } else if (event.type === 'ping') {
    // ...
  }
  // ...
}

es.addEventListener('open', listener);
es.addEventListener('ping', listener);
```

These changes interfere with this approach. However, I've opened another PR that addresses these issues. Please take a moment to review it: https://github.com/binaryminds/react-native-sse/pull/29.

**Comment by EmilJunker** [comment]
@wojciechkrol I'm not a big fan of the implementation in #29

It doesn't let me define an event handler function separately and then assign it like this:

```ts
const myPingHandler: EventSourceListener<'ping'> = (e) => {
    console.log(e.data); // error because property 'data' might not exist
};

es.addEventListener('ping', myPingHandler);
```

Similarly, it doesn't let me define a handler that is just for my custom events like this:

```ts
const myHandlerForCustomEvents: EventSourceListener<MyCustomEvents> = (e) => {
    console.log(e.data); // error because property 'data' might not exist
};

es.addEventListener('ping', myHandlerForCustomEvents);
es.addEventListener('clientConnected', myHandlerForCustomEvents);
es.addEventListener('clientDisconnected', myHandlerForCustomEvents);
```

The implementation by ingvardm lets me do all of these things.

If you want to define one handler for everything, you can simply do it like this:

```ts
const listener: EventSourceListener<MyCustomEvents | EventType> = (event) => {
    // ...
    if (event.type === 'open') {
        // ...
    } else if (event.type === 'ping') {
        // ...
    }
    // ...
};

es.addEventListener('open', listener);
es.addEventListener('message', listener);
es.addEventListener('error', listener);
es.addEventListener('ping', listener);
es.addEventListener('clientConnected', listener);
es.addEventListener('clientDisconnected', listener);
```

**Comment by wojciechkrol** [comment]
First and foremost, `EventSourceListener` is designed to handle all basic events without the need for unnecessary injections. If you want to achieve the effect you've outlined above, you can define it as follows:

```ts
const myPingHandler: EventSourceListener<MyCustomEvents, 'ping'> = (e) => {
  console.log(e.data);
};

es.addEventListener('ping', myPingHandler);
```
and

```ts
const myHandlerForCustomEvents: EventSourceListener<MyCustomEvents, MyCustomEvents> = (e) => {
    console.log(e.data);
};

es.addEventListener('ping', myHandlerForCustomEvents);
es.addEventListener('clientConnected', myHandlerForCustomEvents);
es.addEventListener('clientDisconnected', myHandlerForCustomEvents);
```
and

```ts
const listener: EventSourceListener<MyCustomEvents> = (event) => {
    // ...
    if (event.type === 'open') {
        // ...
    } else if (event.type === 'ping') {
        // ...
    }
    // ...
};

es.addEventListener('open', listener);
es.addEventListener('message', listener);
es.addEventListener('error', listener);
es.addEventListener('ping', listener);
es.addEventListener('clientConnected', listener);
es.addEventListener('clientDisconnected', listener);
```
If you want an approach similar to what you currently have, feel free to create your own type:

```ts
type CustomEventListener<T extends EventType<E>, E extends string = MyCustomEvents> = EventSourceListener<E, T>;
```

Thanks to this, we have additional control over which events are handled by EventSourceListener (type hint in second typed parameter).

**Comment by EmilJunker** [comment]
@wojciechkrol Okay, I see what you did. In that case, I think the code is alright. No objections from my side :)

**Comment by EmilJunker** [comment]
After one night of sleep, allow me to once more explain why I still like the implementation by ingvardm a little bit better. It makes `EventSourceListener` handle exactly those events that I pass as the type parameter. This behavior is simple, predictable, and practical.

If I define the handler function as `const listener: EventSourceListener` it will be able to handle all the default/built-in events. Same if I define it as `const listener: EventSourceListener<EventType>`.

If I define it as `const listener: EventSourceListener<'open' | 'close'>` it will only handle open and close events, so the type is automatically restricted inside the function body.

If I define it as `const listener: EventSourceListener<'ping'>` it will be able to handle only my custom ping events, so it knows that the event object will be of the `CustomEvent<'ping'>` type.

If I define it as `const listener: EventSourceListener<MyCustomEvents>` it will be able to handle all of my custom events. Thus, in the function body, I can be sure that `event.data` will exist without having to check for the exact event type.

If I define it as `const listener: EventSourceListener<EventType | MyCustomEvents>` it will be able to handle all kinds of events, both built-in ones and custom ones.

I know that all of this is also possible with the implementation in #29, but it is more complicated. Especially because there are now two typed parameters `EventSourceListener<E, T>`, and it is not so obvious what each of them does.

**Comment by wojciechkrol** [comment]
Changes made in https://github.com/binaryminds/react-native-sse/pull/29

**Pull request closed without merging**
